Spliced\Bundle\CmsBundle\Entity\MenuItem:
    type: entity
    table: smc_menu_item
    repositoryClass: Spliced\Bundle\CmsBundle\Repository\MenuItemRepository
    indexes:
        menu_id:
            columns:
                - menu_id
        parent_id:
            columns:
                - parent_id
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        position:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
        targetPath:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: target_path
        anchorText:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: anchor_text
        titleText:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: title_text
        options:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    manyToOne:
        menu:
            targetEntity: Menu
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                menu_id:
                    referencedColumnName: id
            orphanRemoval: false
        parent:
            targetEntity: MenuItem
            cascade: {  }
            mappedBy: null
            inversedBy: children
            joinColumns:
                parent_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        children:
          targetEntity: MenuItem
          mappedBy: parent
          cascade: ["persist"]
    lifecycleCallbacks: {  }
