<?php

namespace Spliced\Bundle\ProjectManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{

	public function getListQuery(){
		$query = $this->getEntityManager()->createQueryBuilder()
		  ->select('c, u')
		  ->from('SplicedProjectManagerBundle:Client','c')
		    ->leftJoin('c.user','u');
		 
		return $query;
	}
	
	/**
	 * load
	 * Load a Client with all relational data
	 * @param int $id
	 * @return Project
	 * @throws NoResultException
	 */
	public function load($id){
		return $this->getEntityManager()
		->createQuery('
			SELECT client, projects, projectQuotes
			FROM SplicedProjectManagerBundle:Client client
			LEFT JOIN client.projects projects
			LEFT JOIN projects.quotes projectQuotes
			WHERE client.id = :id')
			->setParameter('id',$id)
			->getSingleResult();
	}
}
