<?php

namespace Spliced\Bundle\ProjectManagerBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * AttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffRepository extends EntityRepository
{

	public function getListQuery(){
		$query = $this->getEntityManager()->createQueryBuilder()
		  ->select('s, u')
		  ->from('SplicedProjectManagerBundle:Staff','s')
		  ->leftJoin('s.user', 'u');
		 
		return $query;
	}

}
