Spliced\Bundle\ProjectManagerBundle\Entity\ProjectTag:
    type: entity
    table: smpm_project_tag
    indexes:
        IDX_B30F6BC5166D1F9C:
            columns:
                - project_id
        IDX_B30F6BC5BAD26311:
            columns:
                - tag_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        project:
            targetEntity: Project
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                project_id:
                    referencedColumnName: id
            orphanRemoval: false
        tag:
            targetEntity: Tag
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tag_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
