Spliced\Bundle\ProjectManagerBundle\Entity\ProjectInvoiceLineItem:
    type: entity
    table: smpm_project_invoice_line_item
    indexes:
        IDX_ABA984022989F1FD:
            columns:
                - invoice_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        sku:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        price:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        quantity:
            type: decimal
            nullable: false
            precision: 10
            scale: 0
            comment: ''
    manyToOne:
        invoice:
            targetEntity: ProjectInvoice
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                invoice_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
