Spliced\Bundle\ProjectManagerBundle\Entity\ProjectNote:
    type: entity
    table: smpm_project_note
    indexes:
        IDX_2AE9778BDE12AB56:
            columns:
                - created_by
        IDX_2AE9778B166D1F9C:
            columns:
                - project_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdBy:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: created_by
        note:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        clientViewable:
            type: boolean
            nullable: true
            comment: ''
            column: client_viewable
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            comment: ''
            column: updated_at
    manyToOne:
        project:
            targetEntity: Project
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                project_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
