Spliced\Bundle\ProjectManagerBundle\Entity\ProjectTimeEntry:
    type: entity
    table: smpm_project_time_entry
    indexes:
        project_id:
            columns:
                - project_id
                - staff_id
        staff_id:
            columns:
                - staff_id
        invoice_id:
            columns:
                - invoice_id
        IDX_FA0EBB3166D1F9C:
            columns:
                - project_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entryDate:
            type: datetime
            nullable: false
            comment: ''
            column: entry_date
        entryTime:
            type: decimal
            nullable: false
            precision: 12
            scale: 4
            comment: ''
            column: entry_time
        entryNote:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: entry_note
    manyToOne:
        project:
            targetEntity: Project
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                project_id:
                    referencedColumnName: id
            orphanRemoval: false
        staff:
            targetEntity: Staff
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                staff_id:
                    referencedColumnName: id
            orphanRemoval: false
        invoice:
            targetEntity: ProjectInvoice
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                invoice_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
